<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ehfaq"
 *
 * Auto generated by Extension Builder 2016-04-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple FAQ',
    'description' => 'Just another FAQ based on the Extras/Fluid combo. Questions and and answers are edited in the BE. ',
    'category' => 'plugin',
    'author' => 'Elmar Hinz Distribution',
    'author_email' => 't3elmar@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
