<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ehfaq"
 *
 * Auto generated by Extension Builder 2016-04-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple FAQ',
    'description' => 'Questions, answers, images and a little animation.
         Just another FAQ based on the Extbase/Fluid combo.
         No FE editing.',
    'category' => 'plugin',
    'author' => 'Elmar Hinz',
    'author_email' => 't3elmar@gmail.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.8',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
